[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
fltk = "^1.3"
fltk-evented = "0.5"
display-info = "0.4.4"
image = "0.24.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
